apiVersion: apps/v1
kind: Deployment
metadata:
  name: conjur-master
  namespace: conjur
  labels:
    app: conjur-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conjur-master
  template:
    metadata:
      labels:
        app: conjur-master
    spec:
      containers:
        - name: conjur
          image: docker.io/library/conjur-appliance:13.4
          imagePullPolicy: Never
          ports:
            - containerPort: 443
            - containerPort: 5432
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"

