apiVersion: v1
kind: Service
metadata:
  name: conjur-service
  namespace: conjur
spec:
  selector:
    app: conjur-master
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30443
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30543
  type: NodePort