- name: Criar diretório para armazenar os arquivos do Conjur
  file:
    path: /opt/conjur/install/
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0755'

- name: Criar diretório para volumes persistentes do Conjur
  file:
    path: /opt/conjur/pods/conjur/
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0755'
