- name: Verificar se o pod do Conjur está rodando
  shell: "kubectl get pods -n conjur -l app=conjur-master -o jsonpath='{.items[0].status.phase}'"
  register: conjur_pod_status
  failed_when: conjur_pod_status.stdout != "Running"
  changed_when: false

- name: Testar a API do Conjur via curl
  shell: "curl -k https://$(kubectl get svc conjur-service -n conjur -o jsonpath='{.spec.clusterIP}'):443/health"
  register: conjur_api_response
  changed_when: false

- name: Exibir resposta da API do Conjur
  debug:
    msg: "Resposta da API: {{ conjur_api_response.stdout }}"

- name: Verificar se o Conjur Master está configurado corretamente
  shell: "kubectl exec -n conjur $(kubectl get pod -n conjur -l app=conjur-master -o jsonpath='{.items[0].metadata.name}') -- evoke role"
  register: conjur_role_check
  failed_when: "'master' not in conjur_role_check.stdout"
  changed_when: false
